"""Public evidence-grounded trusted-memory contracts."""

from .capsule import CapsuleItem, EvidenceCapsule, build_evidence_capsule
from .models import (
    CandidateFact,
    CandidateProposal,
    ConflictGroup,
    ConflictMember,
    ConflictRecord,
    DecisionOutcome,
    FactProvenance,
    FactScope,
    LegacyMemoryView,
    LifecycleTransition,
    LifecycleTransitionCore,
    MemoryOrigin,
    MemoryScope,
    MemoryState,
    RevocationRecord,
    RevocationRecordCore,
    SourceRef,
    SupersessionRecord,
    SupersessionRecordCore,
    TrustedFact,
    TrustedFactCore,
)
from .retrieval import RetrievalItem, RetrievalQuery, RetrievalResult, retrieve_exact

__all__ = [
    "CandidateFact",
    "CandidateProposal",
    "CapsuleItem",
    "ConflictGroup",
    "ConflictMember",
    "ConflictRecord",
    "DecisionOutcome",
    "EvidenceCapsule",
    "FactProvenance",
    "FactScope",
    "LegacyMemoryView",
    "LifecycleTransition",
    "LifecycleTransitionCore",
    "MemoryOrigin",
    "MemoryScope",
    "MemoryState",
    "RetrievalItem",
    "RetrievalQuery",
    "RetrievalResult",
    "RevocationRecord",
    "RevocationRecordCore",
    "SourceRef",
    "SupersessionRecord",
    "SupersessionRecordCore",
    "TrustedFact",
    "TrustedFactCore",
    "build_evidence_capsule",
    "retrieve_exact",
]
