import type { DashboardData, ResearchTask } from "./types";

export const syntheticTask: ResearchTask = {
  id: "ego-lite-001",
  generation: "fixture-generation-001",
  title: "Streaming perception backbone study",
  objective:
    "Replace the LTX2B perception path with a bounded streaming candidate while preserving pose quality.",
  stage: "APPROVAL",
  status: "WAITING_FOR_HUMAN",
  riskLevel: "R2",
  updatedAt: "2026-08-09T12:42:08Z",
  acceptance: [
    { key: "fps", label: "Throughput", operator: "≥", target: 10, unit: "FPS" },
    { key: "mpjpe", label: "MPJPE degradation", operator: "≤", target: 5, unit: "%" },
    { key: "repro", label: "Seed coverage", operator: "=", target: 3, unit: "seeds" },
  ],
  experiments: [
    {
      id: "exp-baseline",
      name: "Frozen baseline",
      variant: "LTX2B + Transformer",
      status: "passed",
      fps: 2.8,
      mpjpe: 41.2,
      latency: 357,
      vram: 21.4,
      gpuLane: "replay/0",
      manifestDigest: "sha256:2f86b7c4",
      seeds: 3,
    },
    {
      id: "exp-a1",
      name: "Candidate A1",
      variant: "MobileNetV4 · TSM · GRU",
      status: "queued",
      gpuLane: "replay/1–2",
      manifestDigest: "sha256:95ab01d2",
      seeds: 3,
    },
    {
      id: "exp-a2",
      name: "Candidate A2",
      variant: "MoViNet-A0 Stream",
      status: "queued",
      gpuLane: "replay/3–4",
      manifestDigest: "sha256:4cd80f11",
      seeds: 3,
    },
    {
      id: "exp-a3",
      name: "Candidate A3",
      variant: "RepViT · TSM · GRU",
      status: "blocked",
      gpuLane: "replay/5–7",
      manifestDigest: "sha256:764cb3aa",
      seeds: 3,
    },
  ],
  evidence: [
    {
      id: "ev-goal",
      kind: "goal",
      label: "Frozen ResearchGoal",
      status: "verified",
      digest: "sha256:5c0b…ae14",
      source: "Research PI role fixture",
      verifiedBy: "browser control fixture",
      createdAt: "12:36:09",
    },
    {
      id: "ev-repo",
      kind: "code",
      label: "Repository snapshot",
      status: "verified",
      digest: "git:9b17…f31a",
      source: "browser fixture · synthetic",
      verifiedBy: "Reviewer role fixture",
      createdAt: "12:37:31",
    },
    {
      id: "ev-dataset",
      kind: "dataset_manifest",
      label: "Dataset manifest",
      status: "verified",
      digest: "sha256:91ac…772d",
      source: "dataset-manifest fixture",
      verifiedBy: "Reviewer role fixture",
      createdAt: "12:38:22",
    },
    {
      id: "ev-plan",
      kind: "config",
      label: "Experiment matrix",
      status: "present",
      digest: "sha256:06aa…4b8c",
      source: "Architect role fixture",
      createdAt: "12:40:17",
    },
    { id: "ev-log", kind: "log", label: "Bounded run log", status: "pending" },
    { id: "ev-metric", kind: "metric", label: "Raw metric bundle", status: "missing" },
    { id: "ev-trace", kind: "trace", label: "Execution trace", status: "pending" },
    { id: "ev-review", kind: "review", label: "Independent review", status: "pending" },
  ],
  trace: [
    {
      id: "tr-1",
      at: "12:36:09.104",
      agent: "Research PI Replay",
      kind: "control",
      target: "fixture.goal.freeze",
      status: "ok",
      message: "Synthetic ResearchGoal restored; acceptance schema locked for browser replay.",
      durationMs: 18,
    },
    {
      id: "tr-2",
      at: "12:37:31.882",
      agent: "Scout Replay",
      kind: "control",
      target: "fixture.repo_snapshot",
      status: "ok",
      message: "Browser fixture returned a synthetic repository snapshot; no MCP call occurred.",
      durationMs: 142,
    },
    {
      id: "tr-3",
      at: "12:38:22.319",
      agent: "Scout Replay",
      kind: "control",
      target: "fixture.dataset_manifest",
      status: "ok",
      message: "A synthetic manifest digest was attached from the browser fixture.",
      durationMs: 67,
    },
    {
      id: "tr-4",
      at: "12:40:17.507",
      agent: "Architect Replay",
      kind: "control",
      target: "fixture.research_plan",
      status: "ok",
      message: "Three bounded synthetic candidate arms were restored from fixture data.",
      durationMs: 213,
    },
    {
      id: "tr-5",
      at: "12:41:54.720",
      agent: "Reviewer Replay",
      kind: "control",
      target: "replay.policy_classify",
      status: "blocked",
      message: "The browser replay pauses at the R2 approval checkpoint.",
      durationMs: 9,
    },
  ],
  resources: [
    { label: "GPU utilization", value: 11, unit: "%", series: [7, 9, 12, 8, 14, 11, 9, 13, 11], note: "synthetic replay" },
    { label: "CPU utilization", value: 94, unit: "%", series: [81, 88, 92, 95, 94, 96, 92, 95, 94], note: "synthetic replay" },
    { label: "Data wait", value: 71, unit: "%", series: [42, 51, 63, 74, 68, 76, 71, 69, 71], note: "synthetic replay" },
  ],
  pendingApproval: {
    id: "apv-0027",
    status: "pending",
    riskLevel: "R2",
    summary: "Launch three bounded experiment arms across a modeled eight-lane GPU plan.",
    expectedDigest: "sha256:06aa4b8c9f0e",
    requestedBy: "Architect role fixture",
    estimatedGpuHours: 24,
    rollbackPoint: "sandbox branch · immutable baseline",
  },
  memoryProposal: {
    title: "Runtime hashing can starve GPU workers",
    observation: "Repeated content hashing at worker startup correlates with CPU saturation in the synthetic failure replay.",
    candidateSkill: "dataset-manifest",
    version: "0.2.0-candidate",
    status: "candidate",
    supportCount: 1,
  },
  evidenceRequired: 7,
  evidencePresent: 3,
  gateStatus: "not_run",
};

export const syntheticDashboard: DashboardData = {
  tasks: [syntheticTask],
  activeTaskId: syntheticTask.id,
  demoMode: true,
  generatedAt: syntheticTask.updatedAt,
  integrations: [
    {
      id: "control-plane",
      name: "Browser replay state machine",
      category: "Core",
      status: "simulated",
      mode: "in-memory fixture",
      detail: "This static session calls no backend API or MCP server. State transitions run only in browser memory.",
    },
    {
      id: "hiclaw",
      name: "HiClaw / AgentTeams",
      category: "Collaboration",
      status: "simulated",
      mode: "identity contract fixture",
      detail: "Role labels are fixture metadata; no live AgentTeams or Matrix session is connected.",
    },
    {
      id: "gpu-runtime",
      name: "8× RTX 4090 runtime",
      category: "Execution",
      status: "simulated",
      mode: "telemetry replay",
      detail: "No GPU host is attached. Resource traces are labeled synthetic.",
    },
    {
      id: "nexa",
      name: "TDSQL Nexa data authority",
      category: "Database",
      status: "unconfigured",
      mode: "PostgreSQL-compatible adapter",
      detail: "No Nexa endpoint is configured in the static page; local replay is not presented as Nexa.",
    },
    {
      id: "tencent-agent-memory",
      name: "TencentDB Agent Memory",
      category: "Memory",
      status: "unconfigured",
      mode: "v3 L0–L3 isolation contract",
      detail: "Per-agent SQLite and FOCUS.md are the browser-visible design; no remote memory receipt exists here.",
    },
    {
      id: "nacos",
      name: "Nacos Skill Registry",
      category: "Skills",
      status: "unconfigured",
      mode: "planned adapter",
      detail: "Skill promotion is local-only; nothing is published to Nacos.",
    },
    {
      id: "higress",
      name: "Higress gateway",
      category: "Credentials",
      status: "unconfigured",
      mode: "planned adapter",
      detail: "No gateway or external credential exchange is active.",
    },
  ],
  runtimeMode: "static_replay",
};
