"""Application service implementing the deterministic ResearchOps workflow."""

import hashlib
import json
import os
import urllib.error
import urllib.request
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

from .errors import ConflictError, PolicyError
from .evaluator import evaluate_paired_metric
from .evidence import REQUIRED_FOR_DECISION, evidence_gate
from .memory import MEMORY_WEIGHTS, require_validated_memory, score_memory
from .models import (
    AcceptanceMetric,
    ApprovalPublic,
    ApprovalRecord,
    ApprovalStatus,
    ArtifactEvidencePayload,
    CandidateArm,
    CreateTaskRequest,
    EvidenceKind,
    EvidenceIngestItem,
    EvidenceRecord,
    FinalizeTaskRequest,
    GateStatus,
    IntegrationState,
    IntegrationTruth,
    MemoryCandidate,
    MemoryRecord,
    MemorySignals,
    MetricEvidencePayload,
    ResearchGoal,
    ReviewEvidencePayload,
    RiskLevel,
    RunManifest,
    Stage,
    TaskRecord,
    utc_now,
)
from .policy import (
    ActionIntent,
    build_approval,
    classify_action,
    consume_approval,
    decide_approval,
    validate_approval_token,
)
from .provenance import canonical_sha256, run_manifest_digest, text_sha256
from .state_machine import next_forward_stage, progress_for, validate_transition
from .store_contract import ResearchStore


DEMO_TASK_ID = "ego-lite-001"
SYNTHETIC_NOTICE = (
    "SYNTHETIC DEMO DATA — metrics and artifacts exercise the control plane; "
    "they are not claims from a physical GPU run."
)
LIVE_NOTICE = (
    "EXTERNAL EVIDENCE TASK — no synthetic evidence is generated by the control plane, "
    "but local hashes do not authenticate the external byte source. Terminal contract decisions "
    "require digest-bound upstream receipts, raw metrics, and independent review."
)
GPU_APPROVAL_ACTION = "gpu.launch_experiment"
GPU_CONFIG_RELATIVE_PATH = "apps/api/fixtures/egolite-mcp-launch.yaml"
GPU_ROLLBACK_POINT = (
    "Restore the baseline-ltx configuration pointer and preserve all failed-run evidence."
)
DIRECT_HTTP = urllib.request.build_opener(urllib.request.ProxyHandler({}))

AGENT_ROLES = [
    ("research-pi", "Research PI", "Decomposes goals and owns state transitions"),
    ("scout-agent", "Scout", "Freezes repository, dataset, and prior-failure context"),
    ("architect-agent", "Experiment Architect", "Creates bounded experiment plans"),
    ("runtime-agent", "Runtime", "Executes allowlisted experiment entrypoints"),
    ("evaluation-agent", "Evaluator", "Computes deterministic metrics and bootstrap CIs"),
    ("reviewer-agent", "Independent Reviewer", "Challenges design and verifies evidence"),
    ("memory-agent", "Memory Curator", "Can append candidates but cannot validate them"),
    (
        "memory-validator",
        "Memory Validator",
        "Promotes candidates only after an independently passed evidence gate",
    ),
]


STAGE_AGENT = {
    Stage.INTAKE: "research-pi",
    Stage.CONTEXT: "scout-agent",
    Stage.PLAN: "architect-agent",
    Stage.PLAN_REVIEW: "reviewer-agent",
    Stage.APPROVAL: "human",
    Stage.EXECUTE: "runtime-agent",
    Stage.OBSERVE: "runtime-agent",
    Stage.EVALUATE: "evaluation-agent",
    Stage.VERIFY: "reviewer-agent",
    Stage.DECIDE: "research-pi",
    Stage.ARCHIVE: "research-pi",
    Stage.MEMORY_SKILL: "memory-agent",
    Stage.COMPLETED: "research-pi",
}


LIVE_EVIDENCE_STAGE = {
    EvidenceKind.DATASET_MANIFEST: "CONTEXT",
    EvidenceKind.CONFIG: "PLAN",
    EvidenceKind.CODE: "EXECUTE",
    EvidenceKind.LOG: "OBSERVE",
    EvidenceKind.TRACE: "OBSERVE",
    EvidenceKind.METRIC: "EVALUATE",
    EvidenceKind.REVIEW: "VERIFY",
}

LIVE_BEFORE_OBSERVE = {
    EvidenceKind.DATASET_MANIFEST,
    EvidenceKind.CONFIG,
    EvidenceKind.CODE,
    EvidenceKind.LOG,
    EvidenceKind.TRACE,
}


class ResearchOpsService:
    def __init__(
        self, store: ResearchStore, approval_hmac_secret: Optional[str] = None
    ) -> None:
        self.store = store
        self.approval_hmac_secret = (
            approval_hmac_secret
            if approval_hmac_secret is not None
            else os.getenv("EGO_MCP_APPROVAL_HMAC_SECRET")
        )
        if self.approval_hmac_secret and len(self.approval_hmac_secret.encode("utf-8")) < 32:
            raise PolicyError(
                "approval_secret_too_short",
                "EGO_MCP_APPROVAL_HMAC_SECRET must contain at least 32 bytes",
            )
        self.ensure_demo()

    def ensure_demo(self) -> None:
        with self.store.transaction():
            if not self.store.list_tasks():
                self.reset_demo("happy_path")

    @staticmethod
    def _goal() -> ResearchGoal:
        return ResearchGoal(
            objective=(
                "Replace EgoLite-PWM's heavy video representation with streaming perception "
                "while reaching at least 10 FPS and limiting MPJPE degradation to 5%."
            ),
            hardware="8x RTX 4090 (declared target; no live GPU attached in local demo)",
            constraints={
                "fps_target": 10.0,
                "max_mpjpe_relative_degradation": 0.05,
                "fixed_split": "egolite-demo-v1",
                "seeds": [17, 23, 42],
                "compute_budget_gpu_hours": 24,
                "execution_boundary": "allowlisted entrypoints only",
            },
            acceptance_metrics=[
                AcceptanceMetric(
                    name="FPS",
                    direction="higher_better",
                    threshold=10.0,
                    unit="frames/second",
                    rule="candidate mean >= 10 FPS",
                ),
                AcceptanceMetric(
                    name="MPJPE",
                    direction="lower_better",
                    threshold=0.05,
                    unit="millimetres",
                    rule="relative candidate degradation <= 5%",
                ),
            ],
            candidate_arms=[
                CandidateArm(
                    id="baseline-ltx",
                    name="LTX2B baseline",
                    description="Frozen baseline; included for comparison only",
                ),
                CandidateArm(
                    id="mobilenetv4-tsm-gru",
                    name="MobileNetV4 + causal TSM + GRU",
                    description="Primary streaming candidate",
                ),
                CandidateArm(
                    id="movinet-a0",
                    name="MoViNet A0 Stream",
                    description="Native streaming comparison arm",
                ),
                CandidateArm(
                    id="repvit-tsm-gru",
                    name="RepViT + causal TSM + GRU",
                    description="Efficient transformer comparison arm",
                ),
            ],
        )

    def reset_demo(
        self, scenario: Literal["happy_path", "insufficient_evidence"] = "happy_path"
    ) -> Dict[str, Any]:
        with self.store.transaction():
            now = utc_now()
            generation = "gen_%s" % uuid.uuid4().hex[:12]
            task = TaskRecord(
                id=DEMO_TASK_ID,
                generation=generation,
                title="EgoLite Streaming Perception",
                objective=self._goal().objective,
                stage=Stage.INTAKE,
                risk_level=RiskLevel.R2,
                goal=self._goal(),
                scenario=scenario,
                synthetic_demo=True,
                data_notice=SYNTHETIC_NOTICE,
                owner_agent="research-pi",
                current_agent="research-pi",
                created_at=now,
                updated_at=now,
            )
            self.store.upsert_seed_task(task)
            self.store.append_event(
                task.id,
                task.generation,
                "demo.reset",
                "system",
                Stage.INTAKE,
                {
                    "scenario": scenario,
                    "synthetic": True,
                    "notice": SYNTHETIC_NOTICE,
                    "audit_history_policy": "prior generations remain append-only",
                },
            )
            self.store.append_event(
                task.id,
                task.generation,
                "research.goal.frozen",
                "research-pi",
                Stage.INTAKE,
                {"goal_digest": canonical_sha256(task.goal), "objective": task.objective},
            )
            return {"reset": True, "task": self.task_view(task)}

    def create_live_task(self, request: CreateTaskRequest) -> Dict[str, Any]:
        """Create a non-synthetic task without reusing the demo upsert path.

        ``CreateTaskRequest.synthetic`` is a required ``Literal[False]`` field.  The
        service therefore cannot silently reinterpret an omitted or truthy flag as a
        live execution claim.
        """

        with self.store.transaction():
            now = utc_now()
            generation = "gen_%s" % uuid.uuid4().hex[:12]
            task = TaskRecord(
                id=request.task_id,
                generation=generation,
                title=request.title,
                objective=request.objective,
                stage=Stage.INTAKE,
                risk_level=request.risk_level,
                goal=request.goal,
                scenario="external_live",
                synthetic_demo=False,
                data_notice=LIVE_NOTICE,
                owner_agent=request.owner_agent,
                current_agent=request.owner_agent,
                live_source=request.live_source,
                execution_contract=request.execution_contract,
                created_at=now,
                updated_at=now,
            )
            self.store.create_task(task)
            source_payload = request.live_source.model_dump(mode="json")
            contract_payload = request.execution_contract.model_dump(mode="json")
            self.store.append_event(
                task.id,
                task.generation,
                "task.created",
                request.owner_agent,
                Stage.INTAKE,
                {
                    "synthetic": False,
                    "live_source": source_payload,
                    "live_source_digest": canonical_sha256(source_payload),
                    "execution_contract_digest": canonical_sha256(contract_payload),
                    "truth_boundary": LIVE_NOTICE,
                },
            )
            self.store.append_event(
                task.id,
                task.generation,
                "research.goal.frozen",
                request.owner_agent,
                Stage.INTAKE,
                {"goal_digest": canonical_sha256(task.goal), "objective": task.objective},
            )
            return {
                "created": True,
                "truth": "EXTERNAL_LIVE_EVIDENCE_REQUIRED",
                "task": self.task_view(task),
            }

    @staticmethod
    def _approval_public(approval: Optional[ApprovalRecord]) -> Optional[Dict[str, Any]]:
        if approval is None:
            return None
        public = ApprovalPublic.model_validate(approval.model_dump(exclude={"token_hash"}))
        return public.model_dump(mode="json")

    @staticmethod
    def _status(task: TaskRecord, approval: Optional[ApprovalRecord]) -> str:
        if task.stage == Stage.COMPLETED:
            return "completed"
        if task.stage == Stage.APPROVAL:
            if approval and approval.status == ApprovalStatus.DENIED:
                return "blocked"
            return "waiting_approval"
        if task.stage == Stage.VERIFY and task.gate_result.status == GateStatus.FAIL:
            return "blocked"
        return "running"

    def task_view(self, task: TaskRecord, include_evidence: bool = True) -> Dict[str, Any]:
        approval = self.store.latest_approval(task.id, task.generation)
        evidence = self.store.list_evidence(task.id, task.generation)
        memory_candidates = (
            self.store.list_memory_candidates(task.id, task.generation)
            if include_evidence
            else []
        )
        memories = self.store.list_memories(task.id, task.generation) if include_evidence else []
        approval_view = self._approval_public(approval)
        task_payload = task.model_dump(mode="json")
        task_payload.update(
            {
                "status": self._status(task, approval),
                "progress": progress_for(task.stage),
                "pending_approval": approval_view if task.stage == Stage.APPROVAL else None,
                "approval": approval_view,
                "evidence_summary": {
                    "required": sorted(kind.value for kind in REQUIRED_FOR_DECISION),
                    "present": sorted({record.kind.value for record in evidence}),
                    "missing": sorted(
                        kind.value
                        for kind in REQUIRED_FOR_DECISION - {record.kind for record in evidence}
                    ),
                    "gate_status": task.gate_result.status.value,
                    "independent_reviewer": task.gate_result.independent_reviewer,
                },
                "evidence": (
                    [record.model_dump(mode="json") for record in evidence]
                    if include_evidence
                    else []
                ),
                "memory_candidates": [
                    record.model_dump(mode="json") for record in memory_candidates
                ],
                "memories": [record.model_dump(mode="json") for record in memories],
                "verification": (
                    {
                        "status": "CONTRACT_PASS_ORIGIN_UNVERIFIED"
                        if task.stage == Stage.COMPLETED
                        else "ORIGIN_UNVERIFIED",
                        "external_origin_status": "UNVERIFIED",
                        "live_claim_allowed": False,
                    }
                    if not task.synthetic_demo
                    else {
                        "status": "SYNTHETIC_DEMO",
                        "external_origin_status": "NOT_APPLICABLE",
                        "live_claim_allowed": False,
                    }
                ),
            }
        )
        return task_payload

    def list_tasks(self) -> List[Dict[str, Any]]:
        return [self.task_view(task, include_evidence=False) for task in self.store.list_tasks()]

    def get_task(self, task_id: str) -> Dict[str, Any]:
        return self.task_view(self.store.get_task(task_id))

    def _add_evidence(
        self,
        task: TaskRecord,
        kind: EvidenceKind,
        producer_id: str,
        payload: Dict[str, Any],
    ) -> EvidenceRecord:
        artifact_digest = canonical_sha256(payload)
        record = EvidenceRecord(
            id="evd_%s" % uuid.uuid4().hex,
            task_id=task.id,
            generation=task.generation,
            kind=kind,
            producer_id=producer_id,
            artifact_digest=artifact_digest,
            payload=payload,
            synthetic=task.synthetic_demo,
        )
        self.store.add_evidence(record)
        self.store.append_event(
            task.id,
            task.generation,
            "evidence.recorded",
            producer_id,
            task.stage,
            {
                "evidence_id": record.id,
                "kind": kind.value,
                "artifact_digest": artifact_digest,
                "synthetic": task.synthetic_demo,
            },
        )
        return record

    def _enter_context(self, task: TaskRecord) -> None:
        manifest = {
            "dataset_id": "egolite-demo-v1",
            "split": "frozen-demo-split",
            "records": 24,
            "content_hash_policy": "publish-time full hash; runtime manifest verification",
            "immutable": True,
            "synthetic": True,
            "notice": SYNTHETIC_NOTICE,
        }
        self._add_evidence(task, EvidenceKind.DATASET_MANIFEST, "scout-agent", manifest)

    def _enter_plan(self, task: TaskRecord) -> None:
        config = {
            "schema": "experiment-plan/v1",
            "candidate": "mobilenetv4-tsm-gru",
            "baseline": "baseline-ltx",
            "seeds": [17, 23, 42],
            "gpu_ids": list(range(8)),
            "expected_gpu_hours": 24,
            "metrics": ["FPS", "MPJPE", "latency", "VRAM"],
            "arbitrary_shell": False,
            "synthetic": True,
        }
        self._add_evidence(task, EvidenceKind.CONFIG, "architect-agent", config)

    def _enter_plan_review(self, task: TaskRecord) -> None:
        configs = [
            record
            for record in self.store.list_evidence(task.id, task.generation)
            if record.kind == EvidenceKind.CONFIG
        ]
        if not configs:
            raise ConflictError(
                "plan_evidence_missing",
                "PLAN_REVIEW requires an architect-produced config artifact",
            )
        plan = configs[-1]
        self.store.append_event(
            task.id,
            task.generation,
            "plan.review.passed",
            "reviewer-agent",
            Stage.PLAN_REVIEW,
            {
                "phase": "plan",
                "independent": True,
                "reviewed_producer": plan.producer_id,
                "config_evidence_id": plan.id,
                "config_digest": plan.artifact_digest,
                "verdict": "PASS",
                "findings": [
                    {
                        "severity": "WARN",
                        "code": "modeled_compute_requires_human_approval",
                    }
                ],
                "synthetic": task.synthetic_demo,
            },
        )

    def _approval_contract(self, task: TaskRecord) -> Dict[str, Any]:
        if not task.synthetic_demo:
            execution = task.execution_contract
            if execution is None:
                raise PolicyError(
                    "live_execution_contract_missing",
                    "A non-synthetic task cannot enter APPROVAL without an execution contract",
                )
            payload = execution.action_payload
            scope = "%s:%s:%s:%s" % (
                execution.action,
                task.id,
                task.generation,
                canonical_sha256(payload)[:16],
            )
            return {
                "scope": scope,
                "action": execution.action,
                "digest": canonical_sha256(
                    {"action": execution.action, "payload": payload}
                ),
                "config_sha256": execution.config_sha256,
                "action_payload": payload,
                "rollback_point": execution.rollback_point,
                "ttl_seconds": execution.approval_ttl_seconds,
            }
        config_path = Path(__file__).resolve().parent / "fixtures" / "egolite-mcp-launch.yaml"
        config_sha256 = hashlib.sha256(config_path.read_bytes()).hexdigest()
        payload = {
            "experiment_id": "%s-%s" % (task.id, task.generation),
            "idempotency_key": "launch-%s" % task.generation,
            "entrypoint": "benchmark_stream",
            "config_path": GPU_CONFIG_RELATIVE_PATH,
            "config_sha256": config_sha256,
            "gpu_ids": list(range(8)),
            "seed": 42,
            "expected_gpu_hours": 24.0,
            "tags": ["synthetic", "ego-lite"],
        }
        scope = "gpu.launch:%s:%s" % (payload["experiment_id"], payload["idempotency_key"])
        digest = canonical_sha256({"action": GPU_APPROVAL_ACTION, "payload": payload})
        return {
            "scope": scope,
            "action": GPU_APPROVAL_ACTION,
            "digest": digest,
            "config_sha256": config_sha256,
            "action_payload": payload,
            "rollback_point": GPU_ROLLBACK_POINT,
            "ttl_seconds": 900,
        }

    def _enter_approval(self, task: TaskRecord) -> ApprovalRecord:
        contract = self._approval_contract(task)
        if task.synthetic_demo:
            intent = ActionIntent(
                name=GPU_APPROVAL_ACTION,
                mutates_sandbox=True,
                gpu_count=8,
                expected_gpu_hours=24,
            )
            policy = classify_action(intent)
            risk_level = policy.risk_level
            reasons = policy.reasons
        else:
            risk_level = task.risk_level
            reasons = ["explicit external live execution contract"]
        approval = build_approval(
            approval_id="apr_%s" % uuid.uuid4().hex,
            task_id=task.id,
            generation=task.generation,
            risk_level=risk_level,
            scope=contract["scope"],
            action=contract["action"],
            digest=contract["digest"],
            config_sha256=contract["config_sha256"],
            action_payload=contract["action_payload"],
            rollback_point=contract["rollback_point"],
            ttl_seconds=contract["ttl_seconds"],
        )
        self.store.add_approval(approval)
        self.store.append_event(
            task.id,
            task.generation,
            "approval.requested",
            "research-pi",
            Stage.APPROVAL,
            {
                "approval_id": approval.id,
                "risk_level": risk_level.value,
                "action_digest": approval.action_digest,
                "scope": approval.scope,
                "config_sha256": approval.config_sha256,
                "rollback_point": approval.rollback_point,
                "expires_at": approval.expires_at.isoformat(),
                "reasons": reasons,
                "synthetic": task.synthetic_demo,
            },
        )
        return approval

    def _enter_execute(self, task: TaskRecord) -> None:
        code: Dict[str, Any] = {
            "repository": "ego-lite-demo",
            "commit": text_sha256("synthetic-commit:%s" % task.generation)[:40],
            "entrypoint": "benchmark_stream",
            "allowlisted": True,
            "patch_summary": "Wire MobileNetV4 + causal TSM + GRU candidate arm",
            "synthetic": True,
            "notice": SYNTHETIC_NOTICE,
        }
        code_record = self._add_evidence(task, EvidenceKind.CODE, "runtime-agent", code)
        records = self.store.list_evidence(task.id, task.generation)
        config_digest = next(
            record.artifact_digest for record in records if record.kind == EvidenceKind.CONFIG
        )
        dataset_digest = next(
            record.artifact_digest
            for record in records
            if record.kind == EvidenceKind.DATASET_MANIFEST
        )
        manifest = RunManifest(
            git_commit=code["commit"],
            config_sha256=config_digest,
            dataset_manifest_sha256=dataset_digest,
            environment_lock_sha256=text_sha256("python3.9-fastapi-demo-lock"),
            base_model_sha256=text_sha256("synthetic-ltx2b-baseline"),
            seed=42,
        )
        task.run_manifest_digest = run_manifest_digest(manifest)
        self.store.append_event(
            task.id,
            task.generation,
            "experiment.submitted",
            "runtime-agent",
            Stage.EXECUTE,
            {
                "entrypoint": "benchmark_stream",
                "run_manifest": manifest.model_dump(mode="json"),
                "run_manifest_digest": task.run_manifest_digest,
                "code_evidence_id": code_record.id,
                "execution": "synthetic_demo",
            },
        )

    def _enter_observe(self, task: TaskRecord) -> None:
        log_payload = {
            "run_id": "run_%s" % task.generation,
            "exit_code": 0,
            "records": [
                {"step": 1, "gpu_util_pct": 18, "cpu_util_pct": 94},
                {"step": 2, "gpu_util_pct": 71, "cpu_util_pct": 68},
            ],
            "diagnosis": "publish-time dataset hash avoids repeated runtime hashing",
            "synthetic": True,
            "notice": SYNTHETIC_NOTICE,
        }
        self._add_evidence(task, EvidenceKind.LOG, "runtime-agent", log_payload)
        if task.scenario != "insufficient_evidence":
            trace_payload = {
                "trace_id": "trace_%s" % task.generation,
                "root_span": "research.task",
                "spans": [
                    "agent.route",
                    "skill.invoke",
                    "experiment.submit",
                    "experiment.monitor",
                ],
                "run_manifest_digest": task.run_manifest_digest,
                "synthetic": True,
            }
            self._add_evidence(task, EvidenceKind.TRACE, "runtime-agent", trace_payload)

    def _enter_evaluate(self, task: TaskRecord) -> None:
        fps_baseline = [2.7, 2.9, 2.8, 2.6, 3.0, 2.8, 2.9, 2.7]
        fps_candidate = [11.2, 11.8, 11.5, 11.1, 12.0, 11.7, 11.6, 11.4]
        mpjpe_baseline = [43.1, 42.8, 43.4, 42.9, 43.0, 43.3, 42.7, 43.2]
        mpjpe_candidate = [44.2, 43.9, 44.5, 44.0, 44.1, 44.3, 43.8, 44.2]
        evaluations = [
            evaluate_paired_metric(
                "FPS",
                fps_baseline,
                fps_candidate,
                "higher_better",
                10.0,
                seed=2025,
            ),
            evaluate_paired_metric(
                "MPJPE",
                mpjpe_baseline,
                mpjpe_candidate,
                "lower_better",
                0.05,
                seed=2025,
            ),
        ]
        task.latest_evaluation = evaluations
        metric_payload = {
            "evaluator": "paired_bootstrap/v1",
            "deterministic": True,
            "summary_only": False,
            "raw_samples": {
                "FPS": {"baseline": fps_baseline, "candidate": fps_candidate},
                "MPJPE": {"baseline": mpjpe_baseline, "candidate": mpjpe_candidate},
            },
            "results": [result.model_dump(mode="json") for result in evaluations],
            "synthetic": True,
            "notice": SYNTHETIC_NOTICE,
        }
        self._add_evidence(task, EvidenceKind.METRIC, "evaluation-agent", metric_payload)

    def _enter_verify(self, task: TaskRecord) -> None:
        review_payload = {
            "reviewer_id": "reviewer-agent",
            "reviewed_producers": [
                "architect-agent",
                "evaluation-agent",
                "runtime-agent",
                "scout-agent",
            ],
            "independent": True,
            "verdict": "PASS",
            "checks": {
                "split_frozen": True,
                "raw_metrics_present": True,
                "leakage_detected": False,
                "run_manifest_bound": True,
            },
            "synthetic": True,
        }
        self._add_evidence(task, EvidenceKind.REVIEW, "reviewer-agent", review_payload)

    def _refresh_gate(self, task: TaskRecord) -> None:
        task.gate_result = evidence_gate(self.store.list_evidence(task.id, task.generation))
        event_type = (
            "evidence.gate.passed"
            if task.gate_result.status == GateStatus.PASS
            else "evidence.gate.failed"
        )
        self.store.append_event(
            task.id,
            task.generation,
            event_type,
            "reviewer-agent",
            Stage.VERIFY,
            task.gate_result.model_dump(mode="json"),
        )

    def _enter_decide(self, task: TaskRecord, actor: Optional[str] = None) -> None:
        verdicts = {result.verdict for result in task.latest_evaluation}
        if task.latest_evaluation and verdicts == {"PASS"}:
            task.decision = "KEEP"
        elif "FAIL" in verdicts:
            task.decision = "DROP"
        else:
            task.decision = "INCONCLUSIVE"
        self.store.append_event(
            task.id,
            task.generation,
            "decision.committed",
            actor or "research-pi",
            Stage.DECIDE,
            {
                "decision": task.decision,
                "gate_status": task.gate_result.status.value,
                "run_manifest_digest": task.run_manifest_digest,
                "synthetic": task.synthetic_demo,
            },
        )

    def _enter_memory(self, task: TaskRecord) -> None:
        review_id = task.gate_result.independent_reviewer or ""
        evidence = self.store.list_evidence(task.id, task.generation)
        evidence_digest = canonical_sha256(sorted(record.artifact_digest for record in evidence))
        candidates = [
            MemoryCandidate(
                id="memcand_%s" % uuid.uuid4().hex,
                task_id=task.id,
                generation=task.generation,
                memory_type="episodic",
                statement=(
                    "Repeated runtime dataset hashing can starve GPU workers; this demo trace "
                    "is synthetic and must be replaced by physical-run evidence before reuse."
                ),
                component="dataset-loader",
                evidence_digest=evidence_digest,
                review_id=review_id,
            ),
            MemoryCandidate(
                id="memcand_%s" % uuid.uuid4().hex,
                task_id=task.id,
                generation=task.generation,
                memory_type="procedural",
                statement=(
                    "Hash immutable datasets once at publish time and verify the canonical, "
                    "content-addressed manifest at training startup."
                ),
                component="dataset-manifest",
                evidence_digest=evidence_digest,
                review_id=review_id,
            ),
        ]
        for candidate in candidates:
            self.store.add_memory_candidate(candidate)
            self.store.append_event(
                task.id,
                task.generation,
                "memory.candidate.proposed",
                "memory-agent",
                Stage.MEMORY_SKILL,
                {
                    "candidate_id": candidate.id,
                    "type": candidate.memory_type,
                    "evidence_digest": evidence_digest,
                    "review_id": review_id,
                    "status": "candidate",
                },
            )

        require_validated_memory(task.gate_result, review_id)
        for candidate in candidates:
            record = MemoryRecord(
                id="mem_%s" % uuid.uuid4().hex,
                task_id=candidate.task_id,
                generation=candidate.generation,
                memory_type=candidate.memory_type,
                statement=candidate.statement,
                component=candidate.component,
                evidence_digest=candidate.evidence_digest,
                review_id=candidate.review_id,
                validated=True,
                candidate_id=candidate.id,
                validated_by="memory-validator",
            )
            self.store.add_memory(record)
            self.store.append_event(
                task.id,
                task.generation,
                "memory.validated",
                "memory-validator",
                Stage.MEMORY_SKILL,
                {
                    "memory_id": record.id,
                    "candidate_id": candidate.id,
                    "type": record.memory_type,
                    "evidence_digest": evidence_digest,
                    "review_id": review_id,
                },
            )

    @staticmethod
    def _evidence_payload(item: EvidenceIngestItem) -> Dict[str, Any]:
        return item.payload.model_dump(mode="json", by_alias=True)

    def _validate_live_evidence_item(
        self, task: TaskRecord, item: EvidenceIngestItem
    ) -> Dict[str, Any]:
        if task.synthetic_demo:
            raise PolicyError(
                "live_evidence_on_synthetic_task",
                "External live evidence cannot be attached to the synthetic demo task",
            )
        if item.synthetic is not False:
            raise PolicyError(
                "synthetic_evidence_rejected",
                "Live evidence must carry synthetic=false",
            )
        if item.generation != task.generation:
            raise ConflictError(
                "stale_evidence_generation",
                "Evidence belongs to a different task generation",
                {"expected": task.generation, "actual": item.generation},
            )
        payload = self._evidence_payload(item)
        actual_digest = canonical_sha256(payload)
        if actual_digest != item.artifact_digest:
            raise ConflictError(
                "evidence_digest_mismatch",
                "artifact_digest does not match the canonical typed evidence payload",
                {"expected": item.artifact_digest, "actual": actual_digest},
            )

        if item.kind == EvidenceKind.METRIC:
            if not isinstance(item.payload, MetricEvidencePayload):
                raise ConflictError(
                    "evidence_payload_kind_mismatch",
                    "metric evidence requires egoagentos.external-metric-evidence/v1",
                )
        elif item.kind == EvidenceKind.REVIEW:
            if not isinstance(item.payload, ReviewEvidencePayload):
                raise ConflictError(
                    "evidence_payload_kind_mismatch",
                    "review evidence requires egoagentos.external-review-evidence/v1",
                )
        elif not isinstance(item.payload, ArtifactEvidencePayload):
            raise ConflictError(
                "evidence_payload_kind_mismatch",
                "%s evidence requires egoagentos.external-artifact-evidence/v1"
                % item.kind.value,
            )

        expected_stage = LIVE_EVIDENCE_STAGE[item.kind]
        if item.payload.stage != expected_stage:
            raise ConflictError(
                "evidence_stage_mismatch",
                "Typed evidence stage does not match its evidence kind",
                {
                    "kind": item.kind.value,
                    "expected_stage": expected_stage,
                    "actual_stage": item.payload.stage,
                },
            )
        for receipt in item.payload.receipts:
            if not 200 <= receipt.http_status < 300:
                raise ConflictError(
                    "upstream_receipt_failed",
                    "A live evidence receipt records a non-success upstream response",
                    {
                        "source": receipt.source,
                        "operation": receipt.operation,
                        "http_status": receipt.http_status,
                    },
                )
            if not receipt.response_identifier:
                raise ConflictError(
                    "upstream_receipt_identifier_missing",
                    "Every live upstream receipt requires a response identifier",
                    {"source": receipt.source, "operation": receipt.operation},
                )
        if not any(receipt.source == "agentteams" for receipt in item.payload.receipts):
            raise ConflictError(
                "agentteams_receipt_missing",
                "Every live evidence item must be bound to an official AgentTeams response",
                {"kind": item.kind.value},
            )

        if isinstance(item.payload, MetricEvidencePayload):
            if not any(receipt.source == "gpu" for receipt in item.payload.receipts):
                raise ConflictError(
                    "gpu_receipt_missing",
                    "Metric evidence for a live experiment must include a GPU execution receipt",
                )
            raw_samples = {
                name: series.model_dump(mode="json")
                for name, series in item.payload.raw_samples.items()
            }
            if canonical_sha256(raw_samples) != item.payload.raw_metric_digest:
                raise ConflictError(
                    "raw_metric_digest_mismatch",
                    "raw_metric_digest does not match the submitted paired samples",
                )
            result_names = [result.metric for result in item.payload.results]
            if len(result_names) != len(set(result_names)) or set(result_names) != set(raw_samples):
                raise ConflictError(
                    "metric_result_set_mismatch",
                    "Exactly one deterministic result is required for every raw metric series",
                    {"raw_metrics": sorted(raw_samples), "results": result_names},
                )
            for result in item.payload.results:
                series = item.payload.raw_samples[result.metric]
                recomputed = evaluate_paired_metric(
                    result.metric,
                    series.baseline,
                    series.candidate,
                    result.direction,
                    result.threshold,
                    seed=result.bootstrap_seed,
                    iterations=result.bootstrap_samples,
                    data_classification="external_live",
                )
                if recomputed.model_dump(mode="json") != result.model_dump(mode="json"):
                    raise ConflictError(
                        "metric_recompute_mismatch",
                        "Submitted metric result does not match deterministic recomputation",
                        {"metric": result.metric},
                    )
        return payload

    @staticmethod
    def _evidence_by_kind(records: List[EvidenceRecord]) -> Dict[EvidenceKind, EvidenceRecord]:
        indexed: Dict[EvidenceKind, EvidenceRecord] = {}
        for record in records:
            if record.kind in indexed:
                raise ConflictError(
                    "duplicate_evidence_kind",
                    "Live terminal evidence requires exactly one record per kind",
                    {"kind": record.kind.value},
                )
            indexed[record.kind] = record
        return indexed

    def ingest_live_evidence(
        self,
        task_id: str,
        item: EvidenceIngestItem,
        expected_task_version: int,
    ) -> Dict[str, Any]:
        with self.store.transaction():
            task = self.store.get_task(task_id)
            if task.synthetic_demo:
                raise PolicyError(
                    "live_evidence_on_synthetic_task",
                    "External live evidence cannot be attached to the synthetic demo task",
                )
            if task.version != expected_task_version:
                raise ConflictError(
                    "task_version_conflict",
                    "Task changed before evidence ingestion",
                    {"expected": expected_task_version, "actual": task.version},
                )
            allowed_stage = {
                EvidenceKind.DATASET_MANIFEST: Stage.EXECUTE,
                EvidenceKind.CONFIG: Stage.EXECUTE,
                EvidenceKind.CODE: Stage.EXECUTE,
                EvidenceKind.LOG: Stage.EXECUTE,
                EvidenceKind.TRACE: Stage.EXECUTE,
                EvidenceKind.METRIC: Stage.OBSERVE,
                EvidenceKind.REVIEW: Stage.EVALUATE,
            }[item.kind]
            if task.stage != allowed_stage:
                raise ConflictError(
                    "evidence_ingest_stage_conflict",
                    "Evidence cannot be ingested at the current control-plane stage",
                    {
                        "kind": item.kind.value,
                        "expected_stage": allowed_stage.value,
                        "actual_stage": task.stage.value,
                    },
                )
            payload = self._validate_live_evidence_item(task, item)
            existing = self._evidence_by_kind(
                self.store.list_evidence(task.id, task.generation)
            ).get(item.kind)
            if existing is not None:
                if (
                    existing.artifact_digest == item.artifact_digest
                    and existing.producer_id == item.producer_id
                    and existing.payload == payload
                ):
                    return {
                        "receipt": {
                            "schema": "egoagentos.evidence-ingest-receipt/v1",
                            "evidence_id": existing.id,
                            "artifact_digest": existing.artifact_digest,
                            "idempotent_replay": True,
                        },
                        "task": self.task_view(task),
                    }
                raise ConflictError(
                    "evidence_kind_conflict",
                    "A different evidence record already owns this task kind",
                    {"kind": item.kind.value, "evidence_id": existing.id},
                )
            record = self._add_evidence(task, item.kind, item.producer_id, payload)
            if isinstance(item.payload, MetricEvidencePayload):
                task.latest_evaluation = item.payload.results
            old_version = task.version
            task.version += 1
            task.updated_at = utc_now()
            self.store.save_task(task, expected_version=old_version)
            return {
                "receipt": {
                    "schema": "egoagentos.evidence-ingest-receipt/v1",
                    "evidence_id": record.id,
                    "artifact_digest": record.artifact_digest,
                    "idempotent_replay": False,
                },
                "task": self.task_view(task),
            }

    def _validate_live_transition_evidence(
        self, task: TaskRecord, source: Stage, target: Stage
    ) -> None:
        if task.synthetic_demo:
            return
        present = {
            record.kind for record in self.store.list_evidence(task.id, task.generation)
        }
        required: set[EvidenceKind] = set()
        if source == Stage.EXECUTE and target == Stage.OBSERVE:
            required = LIVE_BEFORE_OBSERVE
        elif source == Stage.OBSERVE and target == Stage.EVALUATE:
            required = {EvidenceKind.METRIC}
        elif source == Stage.EVALUATE and target == Stage.VERIFY:
            required = {EvidenceKind.REVIEW}
        missing = required - present
        if missing:
            raise ConflictError(
                "live_stage_evidence_missing",
                "A live task cannot advance without typed evidence for this stage",
                {
                    "from": source.value,
                    "to": target.value,
                    "missing": sorted(kind.value for kind in missing),
                },
            )
        if source == Stage.EVALUATE and target == Stage.VERIFY:
            records = self.store.list_evidence(task.id, task.generation)
            indexed = self._evidence_by_kind(records)
            if REQUIRED_FOR_DECISION - set(indexed):
                raise ConflictError(
                    "terminal_evidence_incomplete",
                    "VERIFY requires all seven typed live evidence kinds",
                )
            review = ReviewEvidencePayload.model_validate(indexed[EvidenceKind.REVIEW].payload)
            expected_digests = {
                record.artifact_digest
                for record in records
                if record.kind != EvidenceKind.REVIEW
            }
            if set(review.reviewed_evidence_digests) != expected_digests:
                raise ConflictError(
                    "review_evidence_set_mismatch",
                    "Independent review does not bind the exact live evidence set",
                )
            gate = evidence_gate(records)
            if gate.status != GateStatus.PASS:
                raise ConflictError(
                    "terminal_evidence_gate_failed",
                    "Live evidence failed integrity or reviewer independence",
                    gate.model_dump(mode="json"),
                )

    def finalize_live_task(self, task_id: str, request: FinalizeTaskRequest) -> Dict[str, Any]:
        with self.store.transaction():
            task = self.store.get_task(task_id)
            if task.synthetic_demo:
                raise PolicyError(
                    "synthetic_task_finalization_forbidden",
                    "The live finalization endpoint cannot be used for the synthetic demo",
                )
            if task.generation != request.generation:
                raise ConflictError(
                    "stale_finalization_generation",
                    "Finalization generation does not match the current task",
                    {"expected": task.generation, "actual": request.generation},
                )
            if task.version != request.expected_task_version:
                raise ConflictError(
                    "task_version_conflict",
                    "Task changed before terminal finalization",
                    {"expected": request.expected_task_version, "actual": task.version},
                )
            if task.stage != Stage.EXECUTE:
                raise ConflictError(
                    "live_finalization_stage_conflict",
                    "Live finalization must begin from EXECUTE after a consumed R2 grant",
                    {"stage": task.stage.value},
                )
            if request.terminal_actor != task.owner_agent:
                raise PolicyError(
                    "terminal_actor_mismatch",
                    "Only the task owner may commit the terminal scientific decision",
                    {"expected": task.owner_agent, "actual": request.terminal_actor},
                )

            incoming: Dict[EvidenceKind, tuple[EvidenceIngestItem, Dict[str, Any]]] = {}
            for item in request.evidence:
                if item.kind in incoming:
                    raise ConflictError(
                        "duplicate_evidence_kind",
                        "Finalization request contains a duplicate evidence kind",
                        {"kind": item.kind.value},
                    )
                incoming[item.kind] = (item, self._validate_live_evidence_item(task, item))

            existing = self._evidence_by_kind(
                self.store.list_evidence(task.id, task.generation)
            )
            candidate_records = list(existing.values())
            new_records: List[EvidenceRecord] = []
            for kind, (item, payload) in incoming.items():
                current = existing.get(kind)
                if current is not None:
                    if not (
                        current.artifact_digest == item.artifact_digest
                        and current.producer_id == item.producer_id
                        and current.payload == payload
                    ):
                        raise ConflictError(
                            "evidence_kind_conflict",
                            "Finalization tried to replace already-ingested evidence",
                            {"kind": kind.value, "evidence_id": current.id},
                        )
                    continue
                record = EvidenceRecord(
                    id="evd_%s" % uuid.uuid4().hex,
                    task_id=task.id,
                    generation=task.generation,
                    kind=kind,
                    producer_id=item.producer_id,
                    artifact_digest=item.artifact_digest,
                    payload=payload,
                    synthetic=False,
                )
                candidate_records.append(record)
                new_records.append(record)

            candidate_by_kind = self._evidence_by_kind(candidate_records)
            missing = REQUIRED_FOR_DECISION - set(candidate_by_kind)
            if missing:
                raise ConflictError(
                    "terminal_evidence_incomplete",
                    "Live finalization requires all seven evidence kinds",
                    {"missing": sorted(kind.value for kind in missing)},
                )
            review = ReviewEvidencePayload.model_validate(
                candidate_by_kind[EvidenceKind.REVIEW].payload
            )
            non_review_digests = {
                record.artifact_digest
                for record in candidate_records
                if record.kind != EvidenceKind.REVIEW
            }
            if set(review.reviewed_evidence_digests) != non_review_digests:
                raise ConflictError(
                    "review_evidence_set_mismatch",
                    "Independent review must bind the exact non-review evidence set",
                    {
                        "expected": sorted(non_review_digests),
                        "actual": sorted(review.reviewed_evidence_digests),
                    },
                )
            gate = evidence_gate(candidate_records)
            if gate.status != GateStatus.PASS:
                raise ConflictError(
                    "terminal_evidence_gate_failed",
                    "Live evidence failed completeness, integrity, or reviewer independence",
                    gate.model_dump(mode="json"),
                )

            for record in new_records:
                self.store.add_evidence(record)
                self.store.append_event(
                    task.id,
                    task.generation,
                    "evidence.recorded",
                    record.producer_id,
                    task.stage,
                    {
                        "evidence_id": record.id,
                        "kind": record.kind.value,
                        "artifact_digest": record.artifact_digest,
                        "synthetic": False,
                    },
                )
            metric = MetricEvidencePayload.model_validate(
                candidate_by_kind[EvidenceKind.METRIC].payload
            )
            task.latest_evaluation = metric.results
            task.run_manifest_digest = canonical_sha256(
                {
                    "task_id": task.id,
                    "generation": task.generation,
                    "execution_contract": task.execution_contract,
                    "evidence": sorted(
                        record.artifact_digest
                        for record in candidate_records
                        if record.kind != EvidenceKind.REVIEW
                    ),
                }
            )

            transitions: List[Dict[str, Any]] = []
            for target in (
                Stage.OBSERVE,
                Stage.EVALUATE,
                Stage.VERIFY,
                Stage.DECIDE,
                Stage.ARCHIVE,
                Stage.MEMORY_SKILL,
                Stage.COMPLETED,
            ):
                transitions.append(self._transition(task, target, None))
            events = self.store.list_events(task.id, task.generation, 0, 1000)
            terminal_event_hash = events[-1].event_hash if events else ""
            receipt = {
                "schema": "egoagentos.live-finalization-receipt/v1",
                "task_id": task.id,
                "generation": task.generation,
                "synthetic": False,
                "decision": task.decision,
                "contract_gate_status": task.gate_result.status.value,
                "verification_status": "CONTRACT_PASS_ORIGIN_UNVERIFIED",
                "external_origin_status": "UNVERIFIED",
                "live_claim_allowed": False,
                "evidence_digests": {
                    kind.value: record.artifact_digest
                    for kind, record in sorted(
                        candidate_by_kind.items(), key=lambda item: item[0].value
                    )
                },
                "run_manifest_digest": task.run_manifest_digest,
                "terminal_event_hash": terminal_event_hash,
                "task_version": task.version,
            }
            return {"receipt": receipt, "transitions": transitions, "task": self.task_view(task)}

    def _transition(
        self, task: TaskRecord, target: Stage, approval_token: Optional[str]
    ) -> Dict[str, Any]:
        source = task.stage
        validate_transition(source, target)
        self._validate_live_transition_evidence(task, source, target)

        if source == Stage.APPROVAL and target == Stage.EXECUTE:
            approval = self.store.latest_approval(task.id, task.generation)
            if approval is None:
                raise PolicyError("approval_required", "No approval exists for this experiment")
            contract = self._approval_contract(task)
            validate_approval_token(
                approval,
                approval_token,
                task.id,
                task.generation,
                contract["scope"],
                contract["action"],
                contract["digest"],
            )
            consume_approval(approval)
            self.store.save_approval(approval)
            self.store.append_event(
                task.id,
                task.generation,
                "approval.token.consumed",
                approval.approver or "human",
                Stage.APPROVAL,
                {"approval_id": approval.id, "single_use": True, "scope": approval.scope},
            )

        if source == Stage.VERIFY and target == Stage.DECIDE:
            self._refresh_gate(task)
            if task.gate_result.status != GateStatus.PASS:
                old_version = task.version
                task.version += 1
                task.updated_at = utc_now()
                self.store.save_task(task, expected_version=old_version)
                raise ConflictError(
                    "evidence_gate_failed",
                    "Decision is blocked until all raw evidence and independent review are present",
                    task.gate_result.model_dump(mode="json"),
                )

        task.stage = target
        transition_actor = (
            task.owner_agent
            if not task.synthetic_demo and target in {Stage.DECIDE, Stage.ARCHIVE, Stage.COMPLETED}
            else STAGE_AGENT[target]
        )
        task.current_agent = transition_actor

        if target == Stage.APPROVAL:
            self._enter_approval(task)
        elif task.synthetic_demo and target == Stage.CONTEXT:
            self._enter_context(task)
        elif task.synthetic_demo and target == Stage.PLAN:
            self._enter_plan(task)
        elif task.synthetic_demo and target == Stage.PLAN_REVIEW:
            self._enter_plan_review(task)
        elif task.synthetic_demo and target == Stage.EXECUTE:
            self._enter_execute(task)
        elif task.synthetic_demo and target == Stage.OBSERVE:
            self._enter_observe(task)
        elif task.synthetic_demo and target == Stage.EVALUATE:
            self._enter_evaluate(task)
        elif task.synthetic_demo and target == Stage.VERIFY:
            self._enter_verify(task)
        elif target == Stage.DECIDE:
            self._enter_decide(task, transition_actor)
        elif task.synthetic_demo and target == Stage.MEMORY_SKILL:
            self._enter_memory(task)

        old_version = task.version
        task.version += 1
        task.updated_at = utc_now()
        self.store.save_task(task, expected_version=old_version)
        self.store.append_event(
            task.id,
            task.generation,
            "state.transitioned",
            transition_actor,
            target,
            {"from": source.value, "to": target.value, "task_version": task.version},
        )
        return {"from": source.value, "to": target.value}

    def advance(
        self,
        task_id: str,
        target: Optional[Stage] = None,
        approval_token: Optional[str] = None,
    ) -> Dict[str, Any]:
        blocked_error: Optional[ConflictError] = None
        with self.store.transaction():
            task = self.store.get_task(task_id)
            destination = target or next_forward_stage(task.stage)
            if destination is None:
                raise ConflictError(
                    "terminal_task", "Task is already at a terminal stage", {"task_id": task.id}
                )
            try:
                transition = self._transition(task, destination, approval_token)
                response = {"transition": transition, "task": self.task_view(task)}
            except ConflictError as error:
                if error.code != "evidence_gate_failed":
                    raise
                blocked_error = error
                response = {}
        if blocked_error is not None:
            raise blocked_error
        return response

    def autorun(self, task_id: str, approval_token: Optional[str] = None) -> Dict[str, Any]:
        transitions: List[Dict[str, Any]] = []
        token = approval_token
        with self.store.transaction():
            initial = self.store.get_task(task_id)
            if not initial.synthetic_demo:
                raise PolicyError(
                    "live_autorun_forbidden",
                    "Non-synthetic tasks must be advanced by correlated AgentTeams receipts",
                )
            for _ in range(20):
                task = self.store.get_task(task_id)
                if task.stage == Stage.COMPLETED:
                    return {
                        "status": "completed",
                        "paused_reason": None,
                        "transitions": transitions,
                        "task": self.task_view(task),
                    }
                if task.stage == Stage.APPROVAL and not token:
                    return {
                        "status": "paused",
                        "paused_reason": "human_approval_required",
                        "transitions": transitions,
                        "task": self.task_view(task),
                    }
                destination = next_forward_stage(task.stage)
                if destination is None:
                    raise ConflictError("terminal_task", "Task has no forward transition")
                try:
                    transitions.append(self._transition(task, destination, token))
                    if task.stage == Stage.EXECUTE:
                        token = None
                except ConflictError as error:
                    if error.code != "evidence_gate_failed":
                        raise
                    blocked = self.store.get_task(task_id)
                    return {
                        "status": "paused",
                        "paused_reason": "insufficient_evidence",
                        "transitions": transitions,
                        "gate": blocked.gate_result.model_dump(mode="json"),
                        "task": self.task_view(blocked),
                    }
            raise ConflictError(
                "autorun_iteration_limit", "Autorun stopped after reaching its safety iteration cap"
            )

    def decide_approval(
        self, approval_id: str, decision: str, approver: str, expected_digest: str
    ) -> Dict[str, Any]:
        with self.store.transaction():
            approval = self.store.get_approval(approval_id)
            task = self.store.get_task(approval.task_id)
            if task.generation != approval.generation:
                raise PolicyError(
                    "stale_approval",
                    "Approval belongs to an earlier task generation",
                    {
                        "approval_generation": approval.generation,
                        "current_generation": task.generation,
                    },
                )
            try:
                approval, raw_token = decide_approval(
                    approval,
                    decision,
                    approver,
                    expected_digest,
                    hmac_secret=self.approval_hmac_secret,
                )
            except PolicyError:
                if approval.status == ApprovalStatus.EXPIRED:
                    self.store.save_approval(approval)
                raise
            self.store.save_approval(approval)
            self.store.append_event(
                task.id,
                task.generation,
                "approval.%s" % decision,
                approver,
                Stage.APPROVAL,
                {
                    "approval_id": approval.id,
                    "action_digest": approval.action_digest,
                    "risk_level": approval.risk_level.value,
                    "token_issued": raw_token is not None,
                },
            )
            return {
                "approval": self._approval_public(approval),
                "approval_token": raw_token,
                "token_notice": (
                    "Returned once for this response; token is scope-bound and single-use."
                    if raw_token
                    else None
                ),
            }

    def events(self, task_id: str, after_sequence: int = 0, limit: int = 200) -> Dict[str, Any]:
        task = self.store.get_task(task_id)
        events = self.store.list_events(task.id, task.generation, after_sequence, limit)
        return {
            "task_id": task.id,
            "generation": task.generation,
            "append_only": True,
            "hash_chained": True,
            "chain_valid": self.store.verify_event_chain(task.id, task.generation),
            "events": [event.model_dump(mode="json") for event in events],
            "next_after_sequence": events[-1].sequence if events else after_sequence,
        }

    @staticmethod
    def integrations() -> Dict[str, Any]:
        now = datetime.now(timezone.utc)
        definitions = [
            ("hiclaw", "HiClaw / AgentTeams", "collaboration plane", "EGO_HICLAW_URL"),
            ("nacos", "Nacos Skill Registry", "skill registry adapter", "EGO_NACOS_URL"),
            ("higress", "Higress", "credential and MCP gateway", "EGO_HIGRESS_URL"),
        ]
        states = []
        for integration_id, name, role, environment_key in definitions:
            endpoint = os.getenv(environment_key, "").strip()
            configured = bool(endpoint)
            status = (
                IntegrationTruth.CONFIGURED_UNVERIFIED
                if configured
                else IntegrationTruth.NOT_CONFIGURED
            )
            detail = (
                "Endpoint is configured, but this local adapter does not claim a live handshake."
                if configured
                else "Optional external adapter is not configured; deterministic local mode remains available."
            )
            if integration_id == "hiclaw" and configured:
                try:
                    with DIRECT_HTTP.open(endpoint, timeout=3) as response:
                        payload = json.loads(response.read())
                    if not isinstance(payload, dict):
                        raise TypeError("AgentTeams Bridge payload must be an object")
                    team = payload.get("team")
                    if (
                        response.status == 200
                        and payload.get("live") is True
                        and isinstance(team, dict)
                    ):
                        status = IntegrationTruth.READY
                        detail = (
                            "Verified through AgentTeams Bridge: Team %s is %s; "
                            "leaderReady=%s and subordinate Workers=%s/%s."
                            % (
                                team.get("name", "unknown"),
                                team.get("phase", "unknown"),
                                team.get("leaderReady", False),
                                team.get("readyWorkers", 0),
                                team.get("totalWorkers", 0),
                            )
                        )
                    else:
                        status = IntegrationTruth.UNAVAILABLE
                        detail = "AgentTeams Bridge responded without a verified live handshake."
                except (
                    OSError,
                    TypeError,
                    json.JSONDecodeError,
                    urllib.error.URLError,
                ):
                    status = IntegrationTruth.UNAVAILABLE
                    detail = (
                        "AgentTeams Bridge is configured but its live handshake is unavailable."
                    )
            state = IntegrationState(
                id=integration_id,
                name=name,
                role=role,
                status=status,
                endpoint_configured=configured,
                checked_at=now,
                detail=detail,
            )
            states.append(state.model_dump(mode="json"))
        return {
            "mode": "verified_handshake_or_metadata",
            "truth_policy": (
                "No external integration is reported ready without a verified handshake. "
                "This build intentionally performs no fake cloud calls."
            ),
            "items": states,
        }

    def health(self) -> Dict[str, Any]:
        database_ready = self.store.ping()
        return {
            "status": "ok" if database_ready else "degraded",
            "service": "egoagentos-researchops-api",
            "version": "0.2.0",
            "time": utc_now().isoformat(),
            "mode": "deterministic-local",
            "database": {
                "status": "ready" if database_ready else "unavailable",
                "engine": self.store.engine,
                "location": self.store.location,
                "audit_events": self.store.audit_guarantee,
            },
            "external_integrations": self.integrations(),
        }

    def dashboard(self) -> Dict[str, Any]:
        tasks = self.store.list_tasks()
        active_stages = {task.current_agent for task in tasks if task.stage != Stage.COMPLETED}
        agents = [
            {
                "id": agent_id,
                "name": name,
                "role": role,
                "status": "active" if agent_id in active_stages else "idle",
            }
            for agent_id, name, role in AGENT_ROLES
        ]
        demo = self.store.get_task(DEMO_TASK_ID)
        recent = self.store.recent_events(20, demo.id, demo.generation)
        return {
            "system": {
                "name": "EgoAgentOS ResearchOps",
                "status": "operational" if self.store.ping() else "degraded",
                "mode": "deterministic-local",
                "principle": "Deterministic Core + LLM Residual",
            },
            "demo": {
                "task_id": DEMO_TASK_ID,
                "generation": demo.generation,
                "synthetic": True,
                "notice": SYNTHETIC_NOTICE,
                "scenario": demo.scenario,
            },
            "active_task_id": demo.id,
            "counts": self.store.counts(),
            "tasks": [self.task_view(task, include_evidence=False) for task in tasks],
            "agents": agents,
            "risk_policy": {
                "R0": "read-only; automatic",
                "R1": "bounded sandbox mutation; automatic",
                "R2": "expensive or significant mutation; human approval",
                "R3": "critical action; approval + rollback point + audit",
            },
            "evidence_gate": {
                "required": sorted(kind.value for kind in REQUIRED_FOR_DECISION),
                "independent_review_required": True,
                "llm_summary_counts_as_metric": False,
            },
            "memory_scoring": {
                "weights": MEMORY_WEIGHTS,
                "example_score": score_memory(
                    MemorySignals(
                        semantic=0.9,
                        component=1.0,
                        evidence=0.95,
                        recency=0.8,
                        failure=1.0,
                    )
                ),
            },
            "activity": [event.model_dump(mode="json") for event in recent],
            "integrations": self.integrations(),
        }
